const fs = require("fs");
const path = require("path");

const SKILLS_DIR = path.join(process.env.HOME || "/home/simon_dou", ".hermes", "skills");
const OUTPUT = path.join(process.cwd(), "data", "skills-cache.json");
const CLIENT_OUTPUT = path.join(process.cwd(), "src/lib/skills-data.ts");

function parseFrontmatter(content) {
  const fm = {};
  const match = content.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!match) return fm;
  const lines = match[1].split("\n");
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const colonIdx = line.indexOf(":");
    if (colonIdx <= 0) continue;
    const key = line.slice(0, colonIdx).trim();
    let val = line.slice(colonIdx + 1).trim().replace(/^["']|["']$/g, "");
    if (val.startsWith("[") && val.endsWith("]")) {
      try { fm[key] = JSON.parse(val); } catch(e) { fm[key] = []; }
    } else {
      fm[key] = val;
    }
  }
  return fm;
}

function main() {
  const skills = [];
  const topEntries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });
  for (const entry of topEntries) {
    if (entry.name.startsWith(".") || !entry.isDirectory()) continue;
    const catDir = path.join(SKILLS_DIR, entry.name);
    let entries2;
    try { entries2 = fs.readdirSync(catDir, { withFileTypes: true }); } catch(e) { continue; }
    for (const e2 of entries2) {
      if (e2.name.startsWith(".") || !e2.isDirectory()) continue;
      const skillFile = path.join(catDir, e2.name, "SKILL.md");
      if (!fs.existsSync(skillFile)) continue;
      const stat = fs.statSync(skillFile);
      if (stat.size === 0) continue;
      const raw = fs.readFileSync(skillFile, "utf-8");
      const fm = parseFrontmatter(raw);
      const bodyMatch = raw.match(/^---\s*\n[\s\S]*?\n---\s*\n([\s\S]*)$/);
      const body = bodyMatch ? bodyMatch[1].trim() : "";
      skills.push({
        name: fm["name"] || e2.name,
        slug: e2.name,
        category: entry.name,
        description: fm["description"] || "",
        version: fm["version"] || "1.0.0",
        author: (Array.isArray(fm["author"]) ? fm["author"].join(", ") : fm["author"]) || "Hermes Community",
        license: fm["license"] || "MIT",
        platforms: Array.isArray(fm["platforms"]) ? fm["platforms"] : [],
        tags: Array.isArray(fm["tags"]) ? fm["tags"] : [],
        body,
        relPath: path.relative(SKILLS_DIR, skillFile),
      });
    }
  }

  // Write JSON cache
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, JSON.stringify(skills, null, 2), "utf-8");

  // Write client-side module
  const clientCode = `// Auto-generated by build-skills.js
export interface Skill {
  name: string;
  slug: string;
  category: string;
  description: string;
  version: string;
  author: string;
  license: string;
  platforms: string[];
  tags: string[];
  body: string;
  relPath: string;
}

export const skillsData: Skill[] = ${JSON.stringify(skills, null, 2)};

export function getAllSkills(): Skill[] { return skillsData; }

export function getSkillBySlug(slug: string): Skill | undefined {
  return skillsData.find(s => s.slug === slug);
}

export function getSkillsByCategory(category: string): Skill[] {
  return skillsData.filter(s => s.category === category);
}

export function getAllCategories(): string[] {
  return [...new Set(skillsData.map(s => s.category))].sort();
}

export function searchSkills(query: string): Skill[] {
  const q = query.toLowerCase();
  return skillsData.filter(
    s => s.name.toLowerCase().includes(q) ||
         s.description.toLowerCase().includes(q) ||
         s.tags.some(t => t.toLowerCase().includes(q)) ||
         s.category.toLowerCase().includes(q)
  );
}
`;
  fs.mkdirSync(path.dirname(CLIENT_OUTPUT), { recursive: true });
  fs.writeFileSync(CLIENT_OUTPUT, clientCode, "utf-8");

  console.log(`✅ Scanned ${skills.length} skills`);

  // Copy to public/skills
  const pubDir = path.join(process.cwd(), "public", "skills");
  for (const skill of skills) {
    const srcFile = path.join(SKILLS_DIR, skill.relPath);
    const destDir = path.join(pubDir, skill.category, skill.slug);
    fs.mkdirSync(destDir, { recursive: true });
    fs.copyFileSync(srcFile, path.join(destDir, "SKILL.md"));
  }
  console.log(`📦 Copied to public/skills/`);
}

main();
